// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Synthesizer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Top_Bar;
lv_obj_t *ui_OSC;
lv_obj_t *ui_OSC_Label;
lv_obj_t *ui_SFX1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Matrix;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Macro;
lv_obj_t *ui_Macro_Label;
lv_obj_t *ui_Spectrum;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Main_Tabs;
lv_obj_t *ui_Oscillator_Tab;
lv_obj_t *ui_ADSR;
lv_obj_t *ui_ENV_1_Tab_Label;
lv_obj_t *ui_Image1;
lv_obj_t *ui_ENV_2_Tab_Label;
lv_obj_t *ui_Image2;
lv_obj_t *ui_ENV_Content_Container;
lv_obj_t *ui_Env_1_Release;
lv_obj_t *ui_Env_1_Release_Time;
lv_obj_t *ui_Env_1_Release_Level;
lv_obj_t *ui_Env_1_Sustain;
lv_obj_t *ui_Env_1_Sustain_Time;
lv_obj_t *ui_Env_1_Sustain_Level;
lv_obj_t *ui_Env_1_Decay;
lv_obj_t *ui_Env_1_Decay_Time;
lv_obj_t *ui_Env_1_Decay_Level;
lv_obj_t *ui_Env_1_Attack;
lv_obj_t *ui_Env_1_Attack_Time;
lv_obj_t *ui_Env_1_Attack_Level;
lv_obj_t *ui_Env_1_Timings;
lv_obj_t *ui_Env_1_Levels;
lv_obj_t *ui_ENV_1_Graph;
lv_obj_t *ui_ENV_Grid;
lv_obj_t *ui_ENV_Line;
lv_obj_t *ui_Env_0s;
lv_obj_t *ui_Env_1s;
lv_obj_t *ui_Env_2s;
lv_obj_t *ui_Env_3s;
lv_obj_t *ui_ENV_ON_Container;
lv_obj_t *ui_ENV_ON_Label;
lv_obj_t *ui_ENV_OFF_Container;
lv_obj_t *ui_ENV_OFF_Label;
lv_obj_t *ui_MainOsc;
lv_obj_t *ui_OSC_1_Label_Container;
lv_obj_t *ui_OSC_1_Label;
lv_obj_t *ui_OSC_2_Label_Container;
lv_obj_t *ui_OSC_2_Label;
lv_obj_t *ui_Noise_Label_Container;
lv_obj_t *ui_Noise_Label;
lv_obj_t *ui_OSC_Info;
lv_obj_t *ui_OSC_Waveform_Container;
lv_obj_t *ui_OSC_Prev_Waveform;
lv_obj_t *ui_OSC_Next_Waveform;
lv_obj_t *ui_OSC_Waveform;
lv_obj_t *ui_Osc_Level_Label;
lv_obj_t *ui_Osc_Level_Val;
lv_obj_t *ui_Osc_Semi_Label;
lv_obj_t *ui_Osc_Semi_Val;
lv_obj_t *ui_Osc_Fine_Label;
lv_obj_t *ui_Osc_Fine_Val;
lv_obj_t *ui_ModOsc;
lv_obj_t *ui_LFO_1_Label_Container;
lv_obj_t *ui_LFO_1_Label;
lv_obj_t *ui_LFO_2_Label_Container;
lv_obj_t *ui_LFO_2_Label;
lv_obj_t *ui_LFO_Info;
lv_obj_t *ui_LFO_Waveform_Container;
lv_obj_t *ui_LFO_Prev_Waveform;
lv_obj_t *ui_LFO_Next_Waveform;
lv_obj_t *ui_LFO_Waveform;
lv_obj_t *ui_LFO_Freq_Label;
lv_obj_t *ui_LFO_Freq_Val;
lv_obj_t *ui_LFO_ON_Container;
lv_obj_t *ui_LFO_ON_Label;
lv_obj_t *ui_LFO_OFF_Container;
lv_obj_t *ui_LFO_OFF_Label;
lv_obj_t *ui_FX_Tab;
lv_obj_t *ui_FX_Page_1_Led;
lv_obj_t *ui_FX_Page_2_Led;
lv_obj_t *ui_FX_Tabs;
lv_obj_t *ui_FX_Page_1;
lv_obj_t *ui_Portamento;
lv_obj_t *ui_Portamento_Settings;
lv_obj_t *ui_Portamento_Time_Label;
lv_obj_t *ui_Portamento_Time_Val;
lv_obj_t *ui_Portamento_Title_Container;
lv_obj_t *ui_Portamento_Title;
lv_obj_t *ui_Separator;
lv_obj_t *ui_Pre_Dist;
lv_obj_t *ui_Pre_Dist_Title_Container;
lv_obj_t *ui_Pre_Dist_Title;
lv_obj_t *ui_Separator1;
lv_obj_t *ui_Pre_Dist_Type_Container;
lv_obj_t *ui_Pre_Dist_Clip_Label_Container;
lv_obj_t *ui_Pre_Dist_Clip_Label;
lv_obj_t *ui_Pre_Dist_Foldback_Label_Container;
lv_obj_t *ui_Pre_Dist_Foldback_Label;
lv_obj_t *ui_Pre_Dist_Drive_Label;
lv_obj_t *ui_Pre_Drive_Slider;
lv_obj_t *ui_Filter;
lv_obj_t *ui_Filter_Settings;
lv_obj_t *ui_LP_Label_Container;
lv_obj_t *ui_LP_Label;
lv_obj_t *ui_HP_Label_Container;
lv_obj_t *ui_HP_Label;
lv_obj_t *ui_BP_Label_Container;
lv_obj_t *ui_BP_Label;
lv_obj_t *ui_Notch_Label_Container;
lv_obj_t *ui_Notch_Label;
lv_obj_t *ui_Cutoff_Container;
lv_obj_t *ui_Filter_Cutoff_Label;
lv_obj_t *ui_Cutoff_Slider;
lv_obj_t *ui_Res_Container;
lv_obj_t *ui_Filter_Resonance_Label;
lv_obj_t *ui_Res_Slider;
lv_obj_t *ui_Filter_Title_Container;
lv_obj_t *ui_Filter_Title;
lv_obj_t *ui_Separator2;
lv_obj_t *ui_FX_Page_2;
lv_obj_t *ui_Post_Dist;
lv_obj_t *ui_Post_Dist_Title_Container;
lv_obj_t *ui_Post_Dist_Title;
lv_obj_t *ui_Separator3;
lv_obj_t *ui_Post_Dist_Type_Container;
lv_obj_t *ui_Post_Dist_Clip_Label_Container;
lv_obj_t *ui_Post_Dist_Clip_Label;
lv_obj_t *ui_Post_Dist_Foldback_Label_Container;
lv_obj_t *ui_Post_Dist_Foldback_Label;
lv_obj_t *ui_Post_Dist_Drive_Label;
lv_obj_t *ui_Post_Drive_Slider;
lv_obj_t *ui_Matrix_Tab;
lv_obj_t *ui_Matrix_Page_1_Led;
lv_obj_t *ui_Matrix_Page_2_Led;
lv_obj_t *ui_Matrix_Page_3_Led;
lv_obj_t *ui_Matrix_Page_4_Led;
lv_obj_t *ui_Matrix_Page_5_Led;
lv_obj_t *ui_Matrix_Pages;
lv_obj_t *ui_Matrix_Page_1;
lv_obj_t *ui_MatrixElementComponent;
lv_obj_t *ui_MatrixElementComponent1;
lv_obj_t *ui_MatrixElementComponent2;
lv_obj_t *ui_MatrixElementComponent3;
lv_obj_t *ui_Matrix_Page_2;
lv_obj_t *ui_MatrixElementComponent4;
lv_obj_t *ui_MatrixElementComponent5;
lv_obj_t *ui_MatrixElementComponent6;
lv_obj_t *ui_MatrixElementComponent7;
lv_obj_t *ui_Matrix_Page_3;
lv_obj_t *ui_MatrixElementComponent8;
lv_obj_t *ui_MatrixElementComponent9;
lv_obj_t *ui_MatrixElementComponent10;
lv_obj_t *ui_MatrixElementComponent11;
lv_obj_t *ui_Matrix_Page_4;
lv_obj_t *ui_MatrixElementComponent12;
lv_obj_t *ui_MatrixElementComponent13;
lv_obj_t *ui_MatrixElementComponent14;
lv_obj_t *ui_MatrixElementComponent15;
lv_obj_t *ui_Matrix_Page_5;
lv_obj_t *ui_MatrixElementComponent16;
lv_obj_t *ui_MatrixElementComponent17;
lv_obj_t *ui_MatrixElementComponent18;
lv_obj_t *ui_MatrixElementComponent19;
lv_obj_t *ui_Macro_Tab;
lv_obj_t *ui_Knob_Page_1_Led;
lv_obj_t *ui_Knob_Page_2_Led;
lv_obj_t *ui_Knob_Page_3_Led;
lv_obj_t *ui_Knob_Page_4_Led;
lv_obj_t *ui_Knob_Page_5_Led;
lv_obj_t *ui_Macro_Pages;
lv_obj_t *ui_Macro_Page_1;
lv_obj_t *ui_MacroElement;
lv_obj_t *ui_MacroElement1;
lv_obj_t *ui_MacroElement2;
lv_obj_t *ui_MacroElement3;
lv_obj_t *ui_Macro_Page_2;
lv_obj_t *ui_MacroElement4;
lv_obj_t *ui_MacroElement5;
lv_obj_t *ui_MacroElement6;
lv_obj_t *ui_MacroElement7;
lv_obj_t *ui_Macro_Page_3;
lv_obj_t *ui_MacroElement8;
lv_obj_t *ui_MacroElement9;
lv_obj_t *ui_MacroElement10;
lv_obj_t *ui_MacroElement11;
lv_obj_t *ui_Macro_Page_4;
lv_obj_t *ui_MacroElement12;
lv_obj_t *ui_MacroElement13;
lv_obj_t *ui_MacroElement14;
lv_obj_t *ui_MacroElement15;
lv_obj_t *ui_Macro_Page_5;
lv_obj_t *ui_MacroElement16;
lv_obj_t *ui_MacroElement17;
lv_obj_t *ui_MacroElement18;
lv_obj_t *ui_MacroElement19;
lv_obj_t *ui_Top_Bar_Line;
lv_obj_t *ui____initial_actions0;


const lv_img_dsc_t *ui_imgset_adsr_bg_220x[1] = {&ui_img_adsr_bg_220x75_png};
const lv_img_dsc_t *ui_imgset_analyzer_bg_transparent_100x[1] = {&ui_img_analyzer_bg_transparent_100x50_png};
const lv_img_dsc_t *ui_imgset_env_[2] = {&ui_img_env_1_png, &ui_img_env_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
