// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Synthesizer

#ifndef _SYNTHESIZER_UI_H
#define _SYNTHESIZER_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_Top_Bar;
    extern lv_obj_t *ui_OSC;
    extern lv_obj_t *ui_OSC_Label;
    extern lv_obj_t *ui_SFX1;
    extern lv_obj_t *ui_Label2;
    extern lv_obj_t *ui_Matrix;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Macro;
    extern lv_obj_t *ui_Macro_Label;
    extern lv_obj_t *ui_Spectrum;
    extern lv_obj_t *ui_Panel1;
    extern lv_obj_t *ui_Panel2;
    extern lv_obj_t *ui_Panel3;
    extern lv_obj_t *ui_Panel4;
    extern lv_obj_t *ui_Panel5;
    extern lv_obj_t *ui_Panel6;
    extern lv_obj_t *ui_Panel7;
    extern lv_obj_t *ui_Panel8;
    extern lv_obj_t *ui_Panel9;
    extern lv_obj_t *ui_Panel10;
    extern lv_obj_t *ui_Main_Tabs;
    extern lv_obj_t *ui_Oscillator_Tab;
    extern lv_obj_t *ui_ADSR;
    extern lv_obj_t *ui_ENV_1_Tab_Label;
    extern lv_obj_t *ui_Image1;
    extern lv_obj_t *ui_ENV_2_Tab_Label;
    extern lv_obj_t *ui_Image2;
    extern lv_obj_t *ui_ENV_Content_Container;
    extern lv_obj_t *ui_Env_1_Release;
    extern lv_obj_t *ui_Env_1_Release_Time;
    extern lv_obj_t *ui_Env_1_Release_Level;
    extern lv_obj_t *ui_Env_1_Sustain;
    extern lv_obj_t *ui_Env_1_Sustain_Time;
    extern lv_obj_t *ui_Env_1_Sustain_Level;
    extern lv_obj_t *ui_Env_1_Decay;
    extern lv_obj_t *ui_Env_1_Decay_Time;
    extern lv_obj_t *ui_Env_1_Decay_Level;
    extern lv_obj_t *ui_Env_1_Attack;
    extern lv_obj_t *ui_Env_1_Attack_Time;
    extern lv_obj_t *ui_Env_1_Attack_Level;
    extern lv_obj_t *ui_Env_1_Timings;
    extern lv_obj_t *ui_Env_1_Levels;
    extern lv_obj_t *ui_ENV_1_Graph;
    extern lv_obj_t *ui_ENV_Grid;
    extern lv_obj_t *ui_ENV_Line;
    extern lv_obj_t *ui_Env_0s;
    extern lv_obj_t *ui_Env_1s;
    extern lv_obj_t *ui_Env_2s;
    extern lv_obj_t *ui_Env_3s;
    extern lv_obj_t *ui_ENV_ON_Container;
    extern lv_obj_t *ui_ENV_ON_Label;
    extern lv_obj_t *ui_ENV_OFF_Container;
    extern lv_obj_t *ui_ENV_OFF_Label;
    extern lv_obj_t *ui_MainOsc;
    extern lv_obj_t *ui_OSC_1_Label_Container;
    extern lv_obj_t *ui_OSC_1_Label;
    extern lv_obj_t *ui_OSC_2_Label_Container;
    extern lv_obj_t *ui_OSC_2_Label;
    extern lv_obj_t *ui_Noise_Label_Container;
    extern lv_obj_t *ui_Noise_Label;
    extern lv_obj_t *ui_OSC_Info;
    extern lv_obj_t *ui_OSC_Waveform_Container;
    extern lv_obj_t *ui_OSC_Prev_Waveform;
    extern lv_obj_t *ui_OSC_Next_Waveform;
    extern lv_obj_t *ui_OSC_Waveform;
    extern lv_obj_t *ui_Osc_Level_Label;
    extern lv_obj_t *ui_Osc_Level_Val;
    extern lv_obj_t *ui_Osc_Semi_Label;
    extern lv_obj_t *ui_Osc_Semi_Val;
    extern lv_obj_t *ui_Osc_Fine_Label;
    extern lv_obj_t *ui_Osc_Fine_Val;
    extern lv_obj_t *ui_ModOsc;
    extern lv_obj_t *ui_LFO_1_Label_Container;
    extern lv_obj_t *ui_LFO_1_Label;
    extern lv_obj_t *ui_LFO_2_Label_Container;
    extern lv_obj_t *ui_LFO_2_Label;
    extern lv_obj_t *ui_LFO_Info;
    extern lv_obj_t *ui_LFO_Waveform_Container;
    extern lv_obj_t *ui_LFO_Prev_Waveform;
    extern lv_obj_t *ui_LFO_Next_Waveform;
    extern lv_obj_t *ui_LFO_Waveform;
    extern lv_obj_t *ui_LFO_Freq_Label;
    extern lv_obj_t *ui_LFO_Freq_Val;
    extern lv_obj_t *ui_LFO_ON_Container;
    extern lv_obj_t *ui_LFO_ON_Label;
    extern lv_obj_t *ui_LFO_OFF_Container;
    extern lv_obj_t *ui_LFO_OFF_Label;
    extern lv_obj_t *ui_FX_Tab;
    extern lv_obj_t *ui_FX_Page_1_Led;
    extern lv_obj_t *ui_FX_Page_2_Led;
    extern lv_obj_t *ui_FX_Tabs;
    extern lv_obj_t *ui_FX_Page_1;
    extern lv_obj_t *ui_Portamento;
    extern lv_obj_t *ui_Portamento_Settings;
    extern lv_obj_t *ui_Portamento_Time_Label;
    extern lv_obj_t *ui_Portamento_Time_Val;
    extern lv_obj_t *ui_Portamento_Title_Container;
    extern lv_obj_t *ui_Portamento_Title;
    extern lv_obj_t *ui_Separator;
    extern lv_obj_t *ui_Pre_Dist;
    extern lv_obj_t *ui_Pre_Dist_Title_Container;
    extern lv_obj_t *ui_Pre_Dist_Title;
    extern lv_obj_t *ui_Separator1;
    extern lv_obj_t *ui_Pre_Dist_Type_Container;
    extern lv_obj_t *ui_Pre_Dist_Clip_Label_Container;
    extern lv_obj_t *ui_Pre_Dist_Clip_Label;
    extern lv_obj_t *ui_Pre_Dist_Foldback_Label_Container;
    extern lv_obj_t *ui_Pre_Dist_Foldback_Label;
    extern lv_obj_t *ui_Pre_Dist_Drive_Label;
    extern lv_obj_t *ui_Pre_Drive_Slider;
    extern lv_obj_t *ui_Filter;
    extern lv_obj_t *ui_Filter_Settings;
    extern lv_obj_t *ui_LP_Label_Container;
    extern lv_obj_t *ui_LP_Label;
    extern lv_obj_t *ui_HP_Label_Container;
    extern lv_obj_t *ui_HP_Label;
    extern lv_obj_t *ui_BP_Label_Container;
    extern lv_obj_t *ui_BP_Label;
    extern lv_obj_t *ui_Notch_Label_Container;
    extern lv_obj_t *ui_Notch_Label;
    extern lv_obj_t *ui_Cutoff_Container;
    extern lv_obj_t *ui_Filter_Cutoff_Label;
    extern lv_obj_t *ui_Cutoff_Slider;
    extern lv_obj_t *ui_Res_Container;
    extern lv_obj_t *ui_Filter_Resonance_Label;
    extern lv_obj_t *ui_Res_Slider;
    extern lv_obj_t *ui_Filter_Title_Container;
    extern lv_obj_t *ui_Filter_Title;
    extern lv_obj_t *ui_Separator2;
    extern lv_obj_t *ui_FX_Page_2;
    extern lv_obj_t *ui_Post_Dist;
    extern lv_obj_t *ui_Post_Dist_Title_Container;
    extern lv_obj_t *ui_Post_Dist_Title;
    extern lv_obj_t *ui_Separator3;
    extern lv_obj_t *ui_Post_Dist_Type_Container;
    extern lv_obj_t *ui_Post_Dist_Clip_Label_Container;
    extern lv_obj_t *ui_Post_Dist_Clip_Label;
    extern lv_obj_t *ui_Post_Dist_Foldback_Label_Container;
    extern lv_obj_t *ui_Post_Dist_Foldback_Label;
    extern lv_obj_t *ui_Post_Dist_Drive_Label;
    extern lv_obj_t *ui_Post_Drive_Slider;
    extern lv_obj_t *ui_Matrix_Tab;
    extern lv_obj_t *ui_Matrix_Page_1_Led;
    extern lv_obj_t *ui_Matrix_Page_2_Led;
    extern lv_obj_t *ui_Matrix_Page_3_Led;
    extern lv_obj_t *ui_Matrix_Page_4_Led;
    extern lv_obj_t *ui_Matrix_Page_5_Led;
    extern lv_obj_t *ui_Matrix_Pages;
    extern lv_obj_t *ui_Matrix_Page_1;
    extern lv_obj_t *ui_MatrixElementComponent;
    extern lv_obj_t *ui_MatrixElementComponent1;
    extern lv_obj_t *ui_MatrixElementComponent2;
    extern lv_obj_t *ui_MatrixElementComponent3;
    extern lv_obj_t *ui_Matrix_Page_2;
    extern lv_obj_t *ui_MatrixElementComponent4;
    extern lv_obj_t *ui_MatrixElementComponent5;
    extern lv_obj_t *ui_MatrixElementComponent6;
    extern lv_obj_t *ui_MatrixElementComponent7;
    extern lv_obj_t *ui_Matrix_Page_3;
    extern lv_obj_t *ui_MatrixElementComponent8;
    extern lv_obj_t *ui_MatrixElementComponent9;
    extern lv_obj_t *ui_MatrixElementComponent10;
    extern lv_obj_t *ui_MatrixElementComponent11;
    extern lv_obj_t *ui_Matrix_Page_4;
    extern lv_obj_t *ui_MatrixElementComponent12;
    extern lv_obj_t *ui_MatrixElementComponent13;
    extern lv_obj_t *ui_MatrixElementComponent14;
    extern lv_obj_t *ui_MatrixElementComponent15;
    extern lv_obj_t *ui_Matrix_Page_5;
    extern lv_obj_t *ui_MatrixElementComponent16;
    extern lv_obj_t *ui_MatrixElementComponent17;
    extern lv_obj_t *ui_MatrixElementComponent18;
    extern lv_obj_t *ui_MatrixElementComponent19;
    extern lv_obj_t *ui_Macro_Tab;
    extern lv_obj_t *ui_Knob_Page_1_Led;
    extern lv_obj_t *ui_Knob_Page_2_Led;
    extern lv_obj_t *ui_Knob_Page_3_Led;
    extern lv_obj_t *ui_Knob_Page_4_Led;
    extern lv_obj_t *ui_Knob_Page_5_Led;
    extern lv_obj_t *ui_Macro_Pages;
    extern lv_obj_t *ui_Macro_Page_1;
    extern lv_obj_t *ui_MacroElement;
    extern lv_obj_t *ui_MacroElement1;
    extern lv_obj_t *ui_MacroElement2;
    extern lv_obj_t *ui_MacroElement3;
    extern lv_obj_t *ui_Macro_Page_2;
    extern lv_obj_t *ui_MacroElement4;
    extern lv_obj_t *ui_MacroElement5;
    extern lv_obj_t *ui_MacroElement6;
    extern lv_obj_t *ui_MacroElement7;
    extern lv_obj_t *ui_Macro_Page_3;
    extern lv_obj_t *ui_MacroElement8;
    extern lv_obj_t *ui_MacroElement9;
    extern lv_obj_t *ui_MacroElement10;
    extern lv_obj_t *ui_MacroElement11;
    extern lv_obj_t *ui_Macro_Page_4;
    extern lv_obj_t *ui_MacroElement12;
    extern lv_obj_t *ui_MacroElement13;
    extern lv_obj_t *ui_MacroElement14;
    extern lv_obj_t *ui_MacroElement15;
    extern lv_obj_t *ui_Macro_Page_5;
    extern lv_obj_t *ui_MacroElement16;
    extern lv_obj_t *ui_MacroElement17;
    extern lv_obj_t *ui_MacroElement18;
    extern lv_obj_t *ui_MacroElement19;
    extern lv_obj_t *ui_Top_Bar_Line;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_analyzer_bg_transparent_100x50_png); // assets/Analyzer BG Transparent 100x50.png
    LV_IMG_DECLARE(ui_img_env_1_png);                          // assets/ENV 1.png
    LV_IMG_DECLARE(ui_img_env_2_png);                          // assets/ENV 2.png
    LV_IMG_DECLARE(ui_img_adsr_bg_220x75_png);                 // assets/ADSR bg 220x75.png
    LV_IMG_DECLARE(ui_img_back_icon_png);                      // assets/Back icon.png
    LV_IMG_DECLARE(ui_img_forward_icon_png);                   // assets/Forward icon.png
    LV_IMG_DECLARE(ui_img_saw_waveform_png);                   // assets/saw waveform.png
    LV_IMG_DECLARE(ui_img_sine_waveform_png);                  // assets/sine waveform.png
    LV_IMG_DECLARE(ui_img_square_waveform_png);                // assets/square waveform.png
    LV_IMG_DECLARE(ui_img_triangle_waveform_png);              // assets/triangle waveform.png
    LV_IMG_DECLARE(ui_img_noise_waveform_png);                 // assets/noise waveform.png

    LV_FONT_DECLARE(ui_font_Kallisto_Bold_10);
    LV_FONT_DECLARE(ui_font_Kallisto_Bold_16);
    LV_FONT_DECLARE(ui_font_Kallisto_Heavy_20);
    LV_FONT_DECLARE(ui_font_Kallisto_Medium_14);
    LV_FONT_DECLARE(ui_font_Kallisto_Medium_18);
    LV_FONT_DECLARE(ui_font_Kallisto_Medium_20);
    LV_FONT_DECLARE(ui_font_Arrows_36);

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
