// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Synthesizer

#ifndef _UI_COMP_MATRIXELEMENTCOMPONENT_H
#define _UI_COMP_MATRIXELEMENTCOMPONENT_H

#include "ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

// COMPONENT MatrixElementComponent
#define UI_COMP_MATRIXELEMENTCOMPONENT_MATRIXELEMENTCOMPONENT 0
#define UI_COMP_MATRIXELEMENTCOMPONENT_MATRIX_MOD_DROPDOWN 1
#define UI_COMP_MATRIXELEMENTCOMPONENT_SINGLE_ARROW_LABEL 2
#define UI_COMP_MATRIXELEMENTCOMPONENT_DOUBLE_ARROW_LABEL 3
#define UI_COMP_MATRIXELEMENTCOMPONENT_MATRIX_DEST_DROPDOWN 4
#define UI_COMP_MATRIXELEMENTCOMPONENT_AMOUNT_SLIDER 5
#define _UI_COMP_MATRIXELEMENTCOMPONENT_NUM 6
    lv_obj_t *ui_MatrixElementComponent_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
