// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Synthesizer

#ifndef _UI_COMP_MACROELEMENTCOMPONENT_H
#define _UI_COMP_MACROELEMENTCOMPONENT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MacroElementComponent
#define UI_COMP_MACROELEMENTCOMPONENT_MACROELEMENTCOMPONENT 0
#define UI_COMP_MACROELEMENTCOMPONENT_MACRO_MOD_DROPDOWN 1
#define UI_COMP_MACROELEMENTCOMPONENT_MACRO_DEST_DROPDOWN 2
#define UI_COMP_MACROELEMENTCOMPONENT_AMOUNT_SLIDER 3
#define UI_COMP_MACROELEMENTCOMPONENT_SINGLE_ARROW_LABEL 4
#define _UI_COMP_MACROELEMENTCOMPONENT_NUM 5
lv_obj_t * ui_MacroElementComponent_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
