// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Synthesizer

#include "ui.h"

void ui_comp_MacroElement_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Matrix_Element_Component_create_hook(lv_obj_t * comp)
{
}

void ui_comp_MatrixElementComponent_create_hook(lv_obj_t * comp)
{
}

void ui_comp_MacroElementComponent_create_hook(lv_obj_t * comp)
{
}
